# Generated by Django 3.1.6 on 2021-02-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0003_address_cafeinfo_info_massage_openinghours_phone_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_massage',
            new_name='user_message',
        ),
    ]
